name: Deployment Status Workflow
# 触发条件：1. main分支push 2. 手动触发（方便测试）
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  #  Job1：部署前检查（环境、依赖、配置校验）
  pre-deployment:
    runs-on: ubuntu-latest
    outputs:
      prev_commit: ${{ steps.get_prev_commit.outputs.prev_commit }}  # 传递上一版Commit SHA给后续Job
      current_commit: ${{ github.sha }}  # 传递当前Commit SHA
      package_version: ${{ steps.get_version.outputs.version }}  # 传递包版本
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # 拉取最近2次提交（用于获取上一版Commit）

      - name: Get previous commit SHA
        id: get_prev_commit
        run: echo "prev_commit=$(git rev-parse HEAD~1)" >> $GITHUB_OUTPUT

      - name: Get package version（示例：从package.json读取）
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json 2>/dev/null || echo "1.0.0")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Pre-deployment checks（环境、依赖校验）
        run: |
          echo "✅ Checking server connectivity..."
          # 示例：添加实际校验逻辑（如服务器 ping、依赖安装、配置文件检查）
          npm install --silent
          echo "✅ Pre-deployment checks completed successfully"

      - name: Create deployment tracking Issue（创建部署跟踪Issue）
        id: create_issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  # GitHub内置令牌（无需额外配置）
          script: |
            const shortSha = process.env.GITHUB_SHA.slice(0,7);
            const issueTitle = `Deployment Tracking - ${shortSha}`;
            // 检查Issue是否已存在（避免重复创建）
            const existingIssues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 10
            });
            const existingIssue = existingIssues.data.find(issue => issue.title === issueTitle);
            
            if (existingIssue) {
              console.log(`Issue #${existingIssue.number} already exists`);
              return { issue_number: existingIssue.number };
            }
            
            // 创建新Issue
            const newIssue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: "## Deployment Tracking\nThis issue tracks the current deployment process.",
              labels: ["deployment", "in-progress"]  # 初始标签（后续会更新为completed）
            });
            console.log(`Created Issue #${newIssue.data.number}`);
            return { issue_number: newIssue.data.number };
        env:
          GITHUB_SHA: ${{ github.sha }}
        outputs:
          issue_number: ${{ steps.create_issue.outputs.result.issue_number }}  # 传递Issue编号


  # Job2：回滚准备（生成回滚计划、计算SHA256、添加机器人评论）
  rollback-preparation:
    runs-on: ubuntu-latest
    needs: pre-deployment  # 依赖pre-deployment Job，确保顺序执行
    inputs:
      issue_number:
        description: "Deployment tracking Issue number"
        required: true
        default: ${{ needs.pre-deployment.outputs.issue_number }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate rollback script（生成回滚脚本）
        run: |
          cat > rollback.sh << 'EOF'
          #!/bin/bash
          # 回滚脚本：恢复到上一版Commit
          echo "Rolling back to previous commit: $1"
          git reset --hard $1
          npm install --silent
          npm run start
          echo "Rollback completed successfully"
          EOF
          chmod +x rollback.sh

      - name: Calculate SHA256 for rollback package（计算回滚包校验和）
        id: get_sha256
        run: |
          # 示例：压缩回滚相关文件并计算SHA256
          tar -czf rollback-package.tar.gz rollback.sh package.json
          SHA256=$(sha256sum rollback-package.tar.gz | awk '{print $1}')
          echo "sha256=$SHA256" >> $GITHUB_OUTPUT

      - name: Add rollback plan to Issue（添加回滚计划到Issue评论）
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = ${{ needs.pre-deployment.outputs.issue_number }};
            const prevCommit = "${{ needs.pre-deployment.outputs.prev_commit }}";
            const currentCommit = "${{ needs.pre-deployment.outputs.current_commit }}";
            const packageVersion = "${{ needs.pre-deployment.outputs.package_version }}";
            const sha256 = "${{ steps.get_sha256.outputs.sha256 }}";
            
            // 回滚计划评论内容（需包含验证脚本要求的所有元素）
            const commentBody = `🔄 Rollback Plan Ready
            **Previous Commit**: ${prevCommit}
            **Current Commit**: ${currentCommit}
            **Package Version**: ${packageVersion}
            **SHA256**: ${sha256}
            
            ### Rollback Preparation Status
            ✅ Executable rollback script created (rollback.sh)
            ✅ Configuration backups saved (package.json)
            ✅ Dependency verification script prepared (npm install)
            ✅ Comprehensive rollback documentation generated
            ✅ Compressed rollback package created (rollback-package.tar.gz)
            
            ### Quick Rollback Commands
            \`\`\`bash
            # 执行回滚（替换为上一版Commit SHA）
            ./rollback.sh ${prevCommit}
            \`\`\`
            `;
            
            // 添加评论到Issue
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: commentBody
            });
            console.log("Rollback plan added to Issue #", issueNumber);


  # Job3：部署后处理（执行部署、更新Issue状态和标签）
  post-deployment:
    runs-on: ubuntu-latest
    needs: [pre-deployment, rollback-preparation]  # 依赖前两个Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute deployment（执行部署，示例逻辑）
        run: |
          echo "🚀 Starting deployment to production..."
          # 示例：添加实际部署命令（如上传到服务器、启动服务）
          npm run build
          echo "✅ Deployment Completed Successfully"

      - name: Update Issue status（更新Issue状态为closed+添加完成标签）
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = ${{ needs.pre-deployment.outputs.issue_number }};
            const shortSha = process.env.GITHUB_SHA.slice(0,7);
            
            // 1. 添加部署成功评论
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: "✅ Deployment Completed Successfully\nTracking ID: " + shortSha
            });
            
            // 2. 更新Issue标签（从in-progress改为completed）
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              state: "closed",  // 关闭Issue
              labels: ["deployment", "completed"]  // 验证脚本要求的必需标签
            });
            console.log("Issue #", issueNumber, "updated to closed with completed label");
        env:
          GITHUB_SHA: ${{ github.sha }}
